version: 2.1

commands:
  cc-before-build:
    description: "Code Climate before-build"
    steps:
      - run:
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
  fmt-check:
    description: "Confirma que a formatação do código"
    steps:
      - run: "pipenv run fmt-check"
  lint:
    description: "Confirma que a tipagem do código está correta"
    steps:
      - run: "pipenv run lint"
  isort-check:
    description: "Confirma que a ordem dos imports está correta"
    steps:
      - run: "pipenv run isort-check"
  all-tests:
    description: "Roda todos os testes do projeto (unitários e integração)"
    steps:
      - run: "pipenv run test"

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install pip/pipenv
          command: pip install --user -U pip==19.3.1 pipenv==2018.11.26
      - run:
          name: Install Pipfile.lock
          command: pipenv install --deploy --ignore-pipfile --dev
      - run:
          name: Install project in dev-mode
          command: pipenv run pip install -e .
      - fmt-check
      - isort-check
      - lint
      - cc-before-build
      - all-tests
      - run:
          when: on_success
          command: "./cc-test-reporter after-build --coverage-input-type coverage.py"
workflows:
  version: 2
  test:
    jobs:
      - test
